### ISSUE TITLE
Reviewpad X-Ray link on the README page not working

### ISSUE THREAD

**Issue by shay2025** [reviewpad/reviewpad#611]
**Describe the bug**
The Reviewpad X-Ray link at https://github.com/reviewpad/reviewpad#contributing page is not working. When clicking on the link it shows the message:
```
Error: Error trying to get analysis summary at e.<anonymous> (https://xray.reviewpad.com/static/js/main.522bbfb6.js:2:729943) at u (https://xray.reviewpad.com/static/js/main.522bbfb6.js:2:699228) at Generator._invoke (https://xray.reviewpad.com/static/js/main.522bbfb6.js:2:699016) at Generator.next (https://xray.reviewpad.com/static/js/main.522bbfb6.js:2:699657) at de (https://xray.reviewpad.com/static/js/main.522bbfb6.js:2:727408) at o (https://xray.reviewpad.com/static/js/main.522bbfb6.js:2:727612)
```

**To Reproduce**
1. Open the link https://xray.reviewpad.com/analysis?repository=https%3A%2F%2Fgithub.com%2Freviewpad%2Freviewpad

**Expected behavior**
The page should have no errors.

**Comment by shay2025** [comment]
Solved.
